server:
  port: 8761

eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
    pattern:
      console: "%d [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %-5level [%thread] %logger : %msg%n"
      file: "%d [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] %-5level [%thread] %logger : %msg%n"
    file: /var/log/containers/backend-application.log
    level.org.springframework: 'OFF'